image: Visual Studio 2019
configuration:
  - Release
platform:
  - x86
  - x64
install:
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - vcpkg install gflags:x86-windows-static
  - vcpkg install gflags:x64-windows-static
build:
  project: OP2BitmapConverter.sln
