image: Visual Studio 2019
configuration:
  - Release
platform:
  - x86
  - x64
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: OP2BitmapConverter.sln
